version: 2.1

workflows:
  latest:
    jobs:
      - build_and_push_latest:
          filters:
            branches:
              only:
                - master
  v0.14.5:
    jobs:
      - build_and_push_v0_14_5:
          filters:
            branches:
              only:
                - v0.14.5

jobs:
  build_and_push_latest:
    docker:
      - image: circleci/golang:1.15.6
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13   
      - run:
          name: Build Container
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u $DOCKERHUB_USER --password-stdin
            make build_latest
            docker push ulmefors/kolibri:latest

  build_and_push_v0_14_5:
    docker:
      - image: circleci/golang:1.15.6
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13   
      - run:
          name: Build and Push Container
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u $DOCKERHUB_USER --password-stdin
            make build_tag KOLIBRI_TAG=0.14.5
            docker push ulmefors/kolibri:0.14.5

