version: 2.1

workflows:
  build:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: circleci/golang:1.15.6
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Container
          command: docker build --tag=ulmefors/kolibri -f Dockerfile .

