version: 2.1

workflows:
  build_and_push:
    jobs:
      - build_and_push

jobs:
  build_and_push:
    docker:
      - image: circleci/golang:1.15.6
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13   
      - run:
          name: Build and Push Container
          command: |
            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD 
            docker build --tag=ulmefors/kolibri:latest -f Dockerfile .
            docker push ulmefors/kolibri:latest

